apiVersion: v1
kind: ConfigMap
metadata:
  name: catalogue-app
  namespace: roboshop
data:
  # make the app connect to the MongoDB service in the roboshop namespace
  MONGO_URL: "mongodb://mongoservice:27017/catalogue"
  # optional: explicitly set port (app defaults to 8080 anyway)
  CATALOGUE_SERVER_PORT: "8080"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalogue-app
  namespace: roboshop
  labels:
    app: catalogue-app
    project: roboshop
spec:
  replicas: 2
  selector:
    matchLabels:
      app: catalogue-app
      project: roboshop
  template:
    metadata:
      labels:
        app: catalogue-app
        project: roboshop
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: catalogue
          image: docker.io/sowmya480/catalogue:v1
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: catalogue-app
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-app
  namespace: roboshop
spec:
  type: ClusterIP
  selector:
    app: catalogue-app
    project: roboshop
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
